const types = {
    SET_USER: "SET_USER",
    SET_AUTH: "SET_AUTH",

    SET_DOCTORS: "SET_DOCTORS",
    ADD_DOCTOR: "ADD_DOCTOR",
    UPDATE_DOCTOR: "UPDATE_DOCTOR",

    SET_NURSES: "SET_NURSES",
    ADD_NURSE: "ADD_NURSE",
    UPDATE_NURSE: "UPDATE_NURSE",

    SET_PATIENTS: "SET_PATIENTS",
    ADD_PATIENT: "ADD_PATIENT",
    UPDATE_PATIENT: "UPDATE_PATIENT",
    ADD_MEDICAL_PRESCRIPTION: "ADD_MEDICAL_PRESCRIPTION",
    ADD_TEAM_REPORT: "ADD_TEAM_REPORT",

    SET_ADM: "SET_ADM",
    ADD_ADM: "ADD_ADM",
    UPDATE_ADM: "UPDATE_ADM",

    SET_GROUPS: "SET_GROUPS",

    CLEAR: "CLEAR",
};

export default types;
