const types = {
    SET_USER: "SET_USER",
    SET_AUTH: "SET_AUTH",

    SET_DOCTORS: "SET_DOCTORS",
    ADD_DOCTOR: "ADD_DOCTOR",
    UPDATE_DOCTOR: "UPDATE_DOCTOR",

    SET_NURSES: "SET_NURSES",
    ADD_NURSE: "ADD_NURSE",
    UPDATE_NURSE: "UPDATE_NURSE",

    SET_GROUPS: "SET_GROUPS",

    CLEAR: "CLEAR",
};

export default types;
